this commit involves voting functionality on articles
VarshaJacob/nc-news pull request #4
Opened 2023-01-10 16:08 UTC by VarshaJacob

2023-01-10 16:23 UTC, leekli requested changes
Well done so far Varsha!

Most of the functionality is here however the voting does not optimistically render.... please see my comments in the PR for more info.

Please implement optimistic rendering, and then submit a new pull request tomorrow ready for review.

2023-01-10 16:23 UTC, leekli commented on src/components/SingleArticle.jsx
> +            <ArticleVotes article_id={articleDisplay.article_id} articleVotes={articleDisplay.votes}/>
This is a nice refactor, moving the 2 buttons into their own component - well done!

2023-01-10 16:23 UTC, leekli commented on src/components/ArticleVotes.jsx
> +
Nice work BUT I don't think this is optimistically rendering... if i click the vote up button quite a few times quickly then the button doesn't update just as quick and that's because it's trying do the api call before updating the number of votes visible to me.

You'll need to implement optimistic rendering on this ticket, the notes if needed are: [https://notes.northcoders.com/courses/js-front-end/optimistic-rendering](url)

2023-01-11 09:50 UTC, RichardNeat requested changes
Hi Varsha, we are really close! Your vote count is still not currently rendering optimistically. We are relying on an API call to update the number that is shown to the user. Can we change it so the optimistic number is shown instead? We will need to consider how we can update the state that is being rendered. Drop one of us a message if you need any help :)

2023-01-11 10:47 UTC, merged